server:
  port: 8083

spring:
  datasource:
    username: test
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: mali-admin
      password: pass
    realmImportFile: mali-realm.json
